enum ImageKey {
  PLAYER = 'player',
  PLAYER_DEAD = 'playerDead',
  ENEMY = 'enemy',
  ENEMY_DEAD = 'enemyDead',
  POTION = 'potion',
  STONE_BLOCK_LIGHT = 'stoneBlockLight',
  STONE_BLICK_DARK = 'stoneBlockDark',
  DOOR_CLOSED = 'doorClosed',
  DOOR_OPEN = 'doorOpen',
  SCROLL = 'scroll',
  FIRE_ORB = 'fireOrb',
  GATEWAY = 'gateway',
  DOG = 'dog',
  DOG_DEAD = 'dogDead',
  GRASS_BLOCK = 'grassBlock',
  FIRE_ELEMENTAL = 'fireElemental',
  LABORATORY = 'laboratory',
  FIRE_WAND = 'fireWand',
  PILE_OF_DUST = 'pileOfDust',
  WAND = 'wand',
  WIZARD = 'wizard',
  WIZARD_DEAD = 'wizardDead',
  ICE_ORB = 'iceOrb',
  CHEST = 'chest',
  SWORD = 'sword',
  SWORD_EQUIPED = 'swordEquiped',
  STOOL = 'stool',
  WOOD_TEXTURE = 'woodTexture',
  INNKEEPER = 'innkeeper',
  DOOR_STONE = 'doorStone',
  BARREL = 'barrel',
  VILLAGER = 'villager',
  VILLAGER_DEAD = 'villagerDead',
  TREE = 'tree',
  BOULDER = 'boulder',
  BOAR = 'boar',
  BOAR_DEAD = 'boarDead',
  WOLF = 'wolf',
  WOLF_DEAD = 'wolfDead',
  SKELETON = 'skeleton',
  GROUND_TEXTURE = 'groundTexture',
  WATER_TEXTURE = 'waterTexture',
  IMP = 'imp',
  BONES = 'bones',
  DEMONIC_ORB = 'demonicOrb',
}

type ImageMap = {
  [key in ImageKey]: HTMLImageElement;
};

export { ImageKey, ImageMap };
